import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0A0A0A",
  },
  content: {
    padding: 20,
    gap: 18,
  },
  hero: {
    backgroundColor: "#111827",
    borderRadius: 28,
    padding: 24,
    gap: 14,
    borderWidth: 1,
    borderColor: "#1E293B",
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "800",
  },
  heroBody: {
    color: "#94A3B8",
    fontSize: 16,
    lineHeight: 24,
  },
  heroButtonRow: {
    flexDirection: "row",
    gap: 12,
  },
  primaryButton: {
    backgroundColor: "#2563EB",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 120,
  },
  successButton: {
    backgroundColor: "#22C55E",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  dangerButton: {
    backgroundColor: "#EF4444",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "#334155",
    backgroundColor: "#111827",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 120,
  },
  secondaryButtonText: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "700",
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statCard: {
    backgroundColor: "#111827",
    borderRadius: 20,
    padding: 18,
    minWidth: "47%",
    borderWidth: 1,
    borderColor: "#1E293B",
    gap: 6,
  },
  statCardSuccess: {
    borderColor: "#166534",
  },
  statCardDanger: {
    borderColor: "#7F1D1D",
  },
  statValue: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "800",
  },
  statLabel: {
    color: "#94A3B8",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  section: {
    gap: 12,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "800",
  },
  mutedText: {
    color: "#94A3B8",
    fontSize: 15,
    lineHeight: 22,
  },
  listCard: {
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 18,
    padding: 16,
    gap: 4,
  },
  listTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  listMeta: {
    color: "#94A3B8",
    fontSize: 14,
    lineHeight: 20,
  },
  screenTitle: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "800",
  },
  screenBody: {
    color: "#94A3B8",
    fontSize: 16,
    lineHeight: 24,
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  chapterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  pillActive: {
    backgroundColor: "#2563EB",
    borderColor: "#3B82F6",
  },
  pillMuted: {
    backgroundColor: "#111827",
    borderColor: "#334155",
  },
  pillText: {
    fontSize: 14,
    fontWeight: "700",
  },
  pillTextActive: {
    color: "#FFFFFF",
  },
  pillTextMuted: {
    color: "#CBD5E1",
  },
  summaryCard: {
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#1E293B",
    borderRadius: 22,
    padding: 20,
    gap: 10,
  },
  summaryLine: {
    color: "#E2E8F0",
    fontSize: 15,
  },
  footerButtons: {
    flexDirection: "row",
    gap: 12,
  },
  progressText: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "700",
  },
  progressTrack: {
    height: 10,
    backgroundColor: "#172033",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#3B82F6",
    borderRadius: 999,
  },
  flashcard: {
    minHeight: 360,
    backgroundColor: "#111827",
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: "#1E293B",
    justifyContent: "center",
    gap: 14,
  },
  flashcardLabel: {
    color: "#60A5FA",
    fontSize: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  flashcardWord: {
    color: "#FFFFFF",
    fontSize: 36,
    fontWeight: "800",
  },
  flashcardHint: {
    color: "#94A3B8",
    fontSize: 16,
  },
  flashcardMeta: {
    color: "#CBD5E1",
    fontSize: 20,
  },
  flashcardMeaning: {
    color: "#94A3B8",
    fontSize: 18,
    lineHeight: 26,
  },
  flashcardTag: {
    color: "#93C5FD",
    fontSize: 14,
    fontWeight: "700",
  },
  searchInput: {
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "#334155",
    borderRadius: 18,
    color: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    padding: 20,
  },
});
